# Databricks notebook source
# domain_config
#
# Generic domain constants for the portfolio template.

CTPS_NAME_PATTERN = "CTPS_%"
TITULAR_NOME = "TITULAR GENERICO"
TITULAR_CPF = "00000000000"
TITULAR_DT_NASCIMENTO = "1990-01-01"

PRESTADOR_PRINCIPAL_CNPJ = "11111111111111"
PRESTADOR_PRINCIPAL_NOME = "PORTFOLIO DATA SOLUTIONS LTDA"
PRESTADOR_SECUNDARIO_CNPJ = "22222222222222"
PRESTADOR_SECUNDARIO_NOME = "PORTFOLIO ANALYTICS STUDIO LTDA"

CNPJ_CONTRATADA_EXCLUIR = {
    PRESTADOR_PRINCIPAL_CNPJ,
    PRESTADOR_SECUNDARIO_CNPJ,
}

NF_GAP_MESES = 2

EMPRESA_CNPJ_OVERRIDES = {
    "ORGANIZACAO ALFA": "33333333333333",
    "ORGANIZACAO BETA": "44444444444444",
}

EMPRESA_ALIASES = [
    (r"\\bPORTFOLIO\\s*DATA\\b", PRESTADOR_PRINCIPAL_NOME, "PROPRIA"),
    (r"\\bPORTFOLIO\\s*ANALYTICS\\b", PRESTADOR_SECUNDARIO_NOME, "PROPRIA"),
    (r"\\bCONSULTORIA\\s*ALFA\\b", "CONSULTORIA ALFA LTDA", "CONSULTORIA"),
    (r"\\bCONSULTORIA\\s*BETA\\b", "CONSULTORIA BETA LTDA", "CONSULTORIA"),
    (r"\\bEMPRESA\\s*ALFA\\b", "EMPRESA ALFA S.A.", "EMPREGADORA"),
    (r"\\bEMPRESA\\s*BETA\\b", "EMPRESA BETA LTDA", "EMPREGADORA"),
    (r"\\bCLIENTE\\s*ALFA\\b", "CLIENTE ALFA S.A.", "EMPREGADORA"),
    (r"\\bCLIENTE\\s*BETA\\b", "CLIENTE BETA LTDA", "EMPREGADORA"),
]

CONSULTORIA_CLIENTE_MAP = {
    "55555555555555": "CONSULTORIA ALFA LTDA",
    "66666666666666": "CONSULTORIA BETA LTDA",
}
